# This is a basic workflow to help you get started with Actions

name: Update forked repos

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repos
        uses: actions/checkout@master
        with:
          repository: ihcomega56/pyrsia
          token: ${{secrets.gh_token}}
      - name: Update repo
        run: |
          git remote add pyrsia https://github.com/pyrsia/pyrsia.git
          git fetch pyrsia
          git merge pyrsia/main
          git push origin main
